name: busy_reader
description: Test app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.3
  intl: ^0.17.0
  auto_route: ^5.0.4
  flutter_bloc: ^8.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^5.0.3
  build_runner:

  flutter_lints: ^2.0.0

flutter:

  generate: true

  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - assets/icons/

  fonts:
    - family: Mulish
      fonts:
        - asset: fonts/Mulish/Mulish-Bold.ttf
        - asset: fonts/Mulish/Mulish-SemiBold.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
        - asset: fonts/Montserrat/Montserrat-Medium.ttf
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
